name: CI workflow
on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'
jobs:
  build:
    runs-on: ubuntu-latest
    container: python:3.9-slim
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - run: echo "🛒This step performs checkout"
      - name: Install dependencies
        run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      - run: echo "📋This step installs dependencies"
      - name: Lint with flake8
        run: |
        flake8 service --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 service --count --max-complexity=10 --max-line-length=127 --statistics
      - run: echo "🍏This step is for linting"
      - name: Run unit tests with nose
        run: nosetests -v --with-spec --spec-color --with-coverage --cover-package=app
      - run: echo " 💯This step runs unit tests"

      

